# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/navid/Dev/graphics/gl1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/navid/Dev/graphics/gl1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/navid/Dev/graphics/gl1/CMakeFiles /home/navid/Dev/graphics/gl1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/navid/Dev/graphics/gl1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testas

# Build rule for target.
testas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testas
.PHONY : testas

# fast build rule for target.
testas/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/build
.PHONY : testas/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f glad/CMakeFiles/glad.dir/build.make glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

src/Clock.o: src/Clock.cpp.o
.PHONY : src/Clock.o

# target to build an object file
src/Clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Clock.cpp.o
.PHONY : src/Clock.cpp.o

src/Clock.i: src/Clock.cpp.i
.PHONY : src/Clock.i

# target to preprocess a source file
src/Clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Clock.cpp.i
.PHONY : src/Clock.cpp.i

src/Clock.s: src/Clock.cpp.s
.PHONY : src/Clock.s

# target to generate assembly for a file
src/Clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Clock.cpp.s
.PHONY : src/Clock.cpp.s

src/Cube.o: src/Cube.cpp.o
.PHONY : src/Cube.o

# target to build an object file
src/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Cube.cpp.o
.PHONY : src/Cube.cpp.o

src/Cube.i: src/Cube.cpp.i
.PHONY : src/Cube.i

# target to preprocess a source file
src/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Cube.cpp.i
.PHONY : src/Cube.cpp.i

src/Cube.s: src/Cube.cpp.s
.PHONY : src/Cube.s

# target to generate assembly for a file
src/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Cube.cpp.s
.PHONY : src/Cube.cpp.s

src/GameHost.o: src/GameHost.cpp.o
.PHONY : src/GameHost.o

# target to build an object file
src/GameHost.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/GameHost.cpp.o
.PHONY : src/GameHost.cpp.o

src/GameHost.i: src/GameHost.cpp.i
.PHONY : src/GameHost.i

# target to preprocess a source file
src/GameHost.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/GameHost.cpp.i
.PHONY : src/GameHost.cpp.i

src/GameHost.s: src/GameHost.cpp.s
.PHONY : src/GameHost.s

# target to generate assembly for a file
src/GameHost.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/GameHost.cpp.s
.PHONY : src/GameHost.cpp.s

src/GameObject.o: src/GameObject.cpp.o
.PHONY : src/GameObject.o

# target to build an object file
src/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/GameObject.cpp.o
.PHONY : src/GameObject.cpp.o

src/GameObject.i: src/GameObject.cpp.i
.PHONY : src/GameObject.i

# target to preprocess a source file
src/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/GameObject.cpp.i
.PHONY : src/GameObject.cpp.i

src/GameObject.s: src/GameObject.cpp.s
.PHONY : src/GameObject.s

# target to generate assembly for a file
src/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/GameObject.cpp.s
.PHONY : src/GameObject.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testas.dir/build.make CMakeFiles/testas.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glad"
	@echo "... testas"
	@echo "... src/Clock.o"
	@echo "... src/Clock.i"
	@echo "... src/Clock.s"
	@echo "... src/Cube.o"
	@echo "... src/Cube.i"
	@echo "... src/Cube.s"
	@echo "... src/GameHost.o"
	@echo "... src/GameHost.i"
	@echo "... src/GameHost.s"
	@echo "... src/GameObject.o"
	@echo "... src/GameObject.i"
	@echo "... src/GameObject.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

